name: YouTubeSubtitleLearner
options:
  minimumXcodeGenVersion: 2.37.0
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 16.4
targets:
  YouTubeSubtitleLearner:
    type: application
    platform: iOS
    deploymentTarget: "16.4"
    sources:
      - path: YouTubeSubtitleLearner
        excludes:
          - "**/*.xcassets/**"
          - "**/.DS_Store"
          - "**/*.json" # will be added as resources below
    resources:
      - path: YouTubeSubtitleLearner/Assets.xcassets
      - path: YouTubeSubtitleLearner/subtitles.json
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.YouTubeSubtitleLearner
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: YouTubeSubtitleLearner/Info.plist
      properties:
        UILaunchScreen: {} # simple blank launch screen
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIUserInterfaceStyle: Light
        NSSpeechRecognitionUsageDescription: "音声を解析して字幕を生成する目的で使用します"
        NSMicrophoneUsageDescription: "音声処理（アプリ音声の録音）に使用します"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
    scheme:
      testTargets: []

